# Site Settings
title: "Dr. [Your Name]"
description: "Astrophysicist | Researcher in Black Hole Accretion"
remote_theme: "mmistakes/minimal-mistakes"
logo: "/assets/images/profile.jpg"
url: "https://yourusername.github.io"
baseurl: ""

# Author Profile
author:
  name: "Dr. [Your Name]"
  avatar: "/assets/images/profile.jpg"
  bio: "I study black hole accretion, thermal conduction, and high-energy astrophysics."
  email: "your-email@example.com"
  github: "yourusername"
  linkedin: "your-linkedin-profile"
  google_scholar: "your-google-scholar-profile"
  orcid: "your-orcid-profile"

# Navigation Menu
nav:
  - title: "Home"
    url: /
  - title: "Research"
    url: /research/
  - title: "Publications"
    url: /publications/
  - title: "Contact"
    url: /contact/

# Collections
collections:
  research:
    output: true
    permalink: /research/:path/
  publications:
    output: true
    permalink: /publications/:path/
  contact:
    output: true
    permalink: /contact/

# Sidebar Configuration
defaults:
  - scope:
      path: ""
    values:
      sidebar:
        nav: "main"
  - scope:
      path: "_research"
      type: research
    values:
      toc: true
  - scope:
      path: "_publications"
      type: publications
    values:
      toc: true

# Theme Settings
minimal_mistakes_skin: "default"
search: true
breadcrumbs: true
timezone: "UTC"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-include-cache

# Build Settings
exclude:
  - "node_modules"
  - "vendor"
  - "Gemfile"
  - "Gemfile.lock"
