# Site Settings
title: "Mr. [Monu Singh]"
description: "Astrophysicist | Researcher in Black Hole Accretion"
remote_theme: "mmistakes/minimal-mistakes"
logo: "/assets/images/me.jpg"
url: "https://yourusername.github.io"
baseurl: ""

# Author Profile
author:
  name: "Mr. [Monu Singh]"
  avatar: "/assets/images/me.jpg"
  bio: "I study black hole accretion, thermal conduction, and high-energy astrophysics."
  email: "your-email@example.com"
  github: "yourusername"
  linkedin: "your-linkedin-profile"
  google_scholar: "your-google-scholar-profile"
  orcid: "your-orcid-profile"

# Navigation Menu
nav:
  - title: "Home"
    url: /
  - title: "Research"
    url: /research/
  - title: "Publications"
    url: /publications/
  - title: "Blog"
    url: /blog/
  - title: "Contact"
    url: /contact/

# Sidebar Configuration
defaults:
  - scope:
      path: ""
    values:
      sidebar:
        nav: "main"

# Enable Table of Contents (TOC) for Research and Publications Pages
defaults:
  - scope:
      path: "research.md"
    values:
      toc: true
  - scope:
      path: "publications.md"
    values:
      toc: true

# Theme Settings
minimal_mistakes_skin: "default"
search: true
breadcrumbs: true
timezone: "UTC"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-include-cache

# Build Settings
exclude:
  - "node_modules"
  - "vendor"
  - "Gemfile"
  - "Gemfile.lock"
