# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Monu Singh
email: monu18@iitg.ac.in
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal website. Here, you can find details about my research, publications, and ways to contact me.
twitter_username: me_nalayak
github_username: monusingh7
instagram_username: me_nalayak
minimal_mistakes_skin: air
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - assets/css/custom.css



excerpt: "This post should display a **header with an overlay image**, if the theme supports it."
header:
  overlay_image: "/assets/images/black_hole.png"
  caption: "Photo credit: [**William Alston**](https://communities.springernature.com/posts/x-ray-reverberation-measurements-of-black-hole-mass-and-spin)"
  actions:
    - label: "More Info"
      url: "https://unsplash.com"



# Navigation Menu (Upper Right Side)
header_links:
  - title: "Home"
    url: /
  - title: "Research"
    url: /research/
  - title: "Publications"
    url: /publications/
  - title: "Contact"
    url: /contact/


# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Monu Singh"
  avatar : "/assets/images/me.jpg"
  bio    : "I endeavour to map the concealed terrains of the universe by studying the phenomenon of accretion surrounding black holes."
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/me_nalayak"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/monusingh7"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/me_nalayak"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/me_nalayak"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/monusingh7"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/me_nalayak"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/"
